- hosts: localhost
  connection: local
  become: true

  #  vars:
    # - installed_packages: [htop, zsh, discord]

  pre_tasks:
    - name: update package cache
      package: update_cache=yes
      changed_when: false


  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml

